Combobox fix
teamsnap/teamsnap-ui pull request #862
Opened 2021-09-18 00:24 UTC by LeonardoHabitzreuter

2021-09-18 00:31 UTC, jondauz approved these changes

2021-09-18 00:35 UTC, jondauz commented
Don't forget to update the package number

2021-09-20 18:59 UTC, BillyFigueroa commented on src/js/components/Table/Paginated/PaginatedTable.tsx
> +  // totalItems,
uncomment or delete

2021-09-20 19:00 UTC, BillyFigueroa commented on src/js/components/Table/Paginated/PaginatedTable.tsx
> +  // totalItems: PropTypes.number.isRequired,
uncomment or delete

2021-09-20 19:00 UTC, BillyFigueroa commented on src/js/components/Table/Paginated/PaginatedTable.tsx
> +export default PaginatedTable;
Need a new line

2021-09-20 19:11 UTC, bradcypert commented
>onChange function should only be called when user clicks on "Done" or "Clear" button
This isn't correct. When the user clicks out of the combobox flyout, it needs to apply the filters as well.

2021-09-21 14:40 UTC, jondauz requested changes
One thing to keep in mind is that we have to change anywhere in TeamSnap SPAs that uses the paginated table  to follow this format.

2021-09-21 14:40 UTC, jondauz commented on src/js/components/ComboBox/Combobox.tsx
> -    if (!flyoutVisible) {
We should still keep this so that when clicking outside of the combobox will filter the list.

2021-09-21 14:40 UTC, jondauz commented on src/js/components/ComboBox/Combobox.tsx
> -            <Button onClick={() => toggleFlyout(false)} type="link">
Lets go back to this version so that filters apply whenever the flyout closes.

2021-09-21 19:40 UTC, jondauz approved these changes

2021-09-21 19:41 UTC, merged